<<<<<<< Updated upstream
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package UI;

=======
package UI;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Vector;

import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import javax.swing.JButton;

import Clases.Cola;
import Clases.PCB;
import UI.UI_planificador;
import Planificadores.P_FCFS;
import Planificadores.P_PA;
import Planificadores.P_PNA;
import Planificadores.P_RoundRobin;
import Planificadores.P_SJF;
import Planificadores.P_SRTF;
import javax.swing.ButtonGroup;










>>>>>>> Stashed changes
/**
 *
 * @author Diego A. Vivolo
 */
<<<<<<< Updated upstream
public class Simulador extends java.awt.Frame {

    /**
     * Creates new form Simulador
     */
    public Simulador() {
        initComponents();
    }
=======
public class Simulador extends javax.swing.JFrame {
    
    private UI_planificador planificadorActual;
    
    
    public Simulador() {
        initComponents();
        
        
        
        ButtonGroup grupoAlgoritmos = new ButtonGroup();
        grupoAlgoritmos.add(FCFS);
        grupoAlgoritmos.add(PA);
        grupoAlgoritmos.add(PNA);
        grupoAlgoritmos.add(ROUNDROBIN);
        grupoAlgoritmos.add(SJF);
        grupoAlgoritmos.add(SRTF);

        // 2. Establecer el planificador por defecto
        // (Asegúrate de que FCFS esté seleccionado por defecto en el diseñador)
        FCFS.setSelected(true); // El tuyo ya tiene esto
        
        // ¡IMPORTANTE! 
        // En tu código, todos los botones tienen .setSelected(true)
        // Debes quitárselo a todos menos a FCFS.
        PA.setSelected(false);
        PNA.setSelected(false);
        ROUNDROBIN.setSelected(false);
        SJF.setSelected(false);
        SRTF.setSelected(false);

        // 3. Inicializar la variable
        planificadorActual = new P_FCFS();
    }
    
>>>>>>> Stashed changes

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
<<<<<<< Updated upstream
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
=======
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        N_procesos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        C_procesos = new javax.swing.JMenuItem();
        Cargar_procesos = new javax.swing.JMenuItem();
        G_estadisticas = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        Opciones = new javax.swing.JMenu();
        A_Planificacion = new javax.swing.JMenu();
        FCFS = new javax.swing.JRadioButtonMenuItem();
        PA = new javax.swing.JRadioButtonMenuItem();
        PNA = new javax.swing.JRadioButtonMenuItem();
        ROUNDROBIN = new javax.swing.JRadioButtonMenuItem();
        SJF = new javax.swing.JRadioButtonMenuItem();
        SRTF = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador");
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        N_procesos.setText("Archivo");

        jMenuItem1.setText("Nuevo proceso");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        N_procesos.add(jMenuItem1);

        C_procesos.setText("Configuracion de los procesos");
        N_procesos.add(C_procesos);

        Cargar_procesos.setText("Cargar archivos para los procesos");
        N_procesos.add(Cargar_procesos);

        G_estadisticas.setText("Guardar estadisticas");
        G_estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_estadisticasActionPerformed(evt);
            }
        });
        N_procesos.add(G_estadisticas);

        Salir.setText("Reiniciar");
        N_procesos.add(Salir);

        jMenuItem6.setText("Salir");
        N_procesos.add(jMenuItem6);

        jMenuBar1.add(N_procesos);

        Opciones.setText("Opciones");
        Opciones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                OpcionesMouseDragged(evt);
            }
        });

        A_Planificacion.setText("Algoritmos de planificacion");

        FCFS.setSelected(true);
        FCFS.setText("FCFS");
        FCFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FCFSActionPerformed(evt);
            }
        });
        A_Planificacion.add(FCFS);

        PA.setSelected(true);
        PA.setText("PA");
        PA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAActionPerformed(evt);
            }
        });
        A_Planificacion.add(PA);

        PNA.setSelected(true);
        PNA.setText("PNA");
        PNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PNAActionPerformed(evt);
            }
        });
        A_Planificacion.add(PNA);

        ROUNDROBIN.setSelected(true);
        ROUNDROBIN.setText("ROUNDROBIN");
        ROUNDROBIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ROUNDROBINActionPerformed(evt);
            }
        });
        A_Planificacion.add(ROUNDROBIN);

        SJF.setSelected(true);
        SJF.setText("SJF");
        SJF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SJFActionPerformed(evt);
            }
        });
        A_Planificacion.add(SJF);

        SRTF.setSelected(true);
        SRTF.setText("SRFT");
        SRTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SRTFActionPerformed(evt);
            }
        });
        A_Planificacion.add(SRTF);

        Opciones.add(A_Planificacion);

        jMenu4.setText("Velocidad");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("1 fps");
        jMenu4.add(jRadioButtonMenuItem1);

        Opciones.add(jMenu4);

        jMenuBar1.add(Opciones);

        setJMenuBar(jMenuBar1);
>>>>>>> Stashed changes

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< Updated upstream
    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
=======
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void OpcionesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpcionesMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcionesMouseDragged

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void G_estadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_estadisticasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G_estadisticasActionPerformed

    private void SJFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SJFActionPerformed
        planificadorActual = new P_SJF();
        System.out.println("Planificador cambiado a SJF"); // Para depurar
    }//GEN-LAST:event_SJFActionPerformed

    private void SRTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SRTFActionPerformed
        planificadorActual = new P_SJF();
        System.out.println("Planificador cambiado a SJF"); // Para depurar
    }//GEN-LAST:event_SRTFActionPerformed

    private void FCFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FCFSActionPerformed
        planificadorActual = new P_SJF();
        System.out.println("Planificador cambiado a SJF"); // Para depurar
    }//GEN-LAST:event_FCFSActionPerformed

    private void PAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAActionPerformed
        planificadorActual = new P_PA();
        System.out.println("Planificador cambiado a PNA");
    }//GEN-LAST:event_PAActionPerformed

    private void PNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PNAActionPerformed
        planificadorActual = new P_PNA();
        System.out.println("Planificador cambiado a PNA");
    }//GEN-LAST:event_PNAActionPerformed

    private void ROUNDROBINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ROUNDROBINActionPerformed
        planificadorActual = new P_SJF();
        System.out.println("Planificador cambiado a SJF"); // Para depurar
    }//GEN-LAST:event_ROUNDROBINActionPerformed
>>>>>>> Stashed changes

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
<<<<<<< Updated upstream
=======
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
>>>>>>> Stashed changes
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulador().setVisible(true);
            }
        });
    }

<<<<<<< Updated upstream

    // Variables declaration - do not modify//GEN-BEGIN:variables
=======
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu A_Planificacion;
    private javax.swing.JMenuItem C_procesos;
    private javax.swing.JMenuItem Cargar_procesos;
    private javax.swing.JRadioButtonMenuItem FCFS;
    private javax.swing.JMenuItem G_estadisticas;
    private javax.swing.JMenu N_procesos;
    private javax.swing.JMenu Opciones;
    private javax.swing.JRadioButtonMenuItem PA;
    private javax.swing.JRadioButtonMenuItem PNA;
    private javax.swing.JRadioButtonMenuItem ROUNDROBIN;
    private javax.swing.JRadioButtonMenuItem SJF;
    private javax.swing.JRadioButtonMenuItem SRTF;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
>>>>>>> Stashed changes
    // End of variables declaration//GEN-END:variables
}
